# -*- coding: utf-8 -*-
"""CKD_ML_Humanised.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12f8kpwZS4sQBD0eJh5SregA2aqVBB632

# Machine Learning for Chronic Kidney Disease Outcome Prediction



### Dataset
We use the **Community Screening** split of the [`electricsheepafrica/chronic-kidney-disease`](https://huggingface.co/datasets/electricsheepafrica/chronic-kidney-disease) dataset from HuggingFace — a synthetic dataset generated from real-world epidemiological distributions across African community screening programmes.

## 1. Environment Setup
"""

!pip install datasets imbalanced-learn lightgbm xgboost --quiet

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from datasets import load_dataset

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import mutual_info_classif
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    accuracy_score,
    f1_score
)

from xgboost import XGBClassifier
import lightgbm as lgb

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from imblearn.ensemble import BalancedRandomForestClassifier

# ── Reproducibility ──────────────────────────────────────────────────────────
RANDOM_STATE = 42
TEST_SIZE     = 0.2
N_SPLITS      = 5

print("All libraries imported successfully.")

"""## 2. Data Loading

We load the `community_screening` configuration from the HuggingFace Datasets hub and convert it directly into a pandas DataFrame for familiar tabular manipulation.
"""

community_screening = load_dataset(
    "electricsheepafrica/chronic-kidney-disease",
    "community_screening"
)

df = community_screening["train"].to_pandas()

print(f"Dataset loaded successfully.")
print(f"Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
df.head()

"""## 3. Exploratory Data Analysis


"""

# --- Data types and null counts ---
print("=== Data Info ===")
df.info()

# --- Summary statistics ---
print("=== Descriptive Statistics ===")
df.describe()

# --- Target class distribution ---
outcome_counts = df["outcome"].value_counts()
print("=== Outcome Class Distribution ===")
print(outcome_counts.to_string())
print()
print("=== Class Proportions (%) ===")
print((outcome_counts / len(df) * 100).round(2).to_string())

# Visualise
fig, ax = plt.subplots(figsize=(7, 4))
outcome_counts.plot(kind="bar", ax=ax, color=["#4C72B0","#DD8452","#55A868","#C44E52"], edgecolor="white")
ax.set_title("CKD Outcome Class Distribution", fontsize=13, weight="bold")
ax.set_xlabel("Outcome")
ax.set_ylabel("Number of Patients")
ax.tick_params(axis="x", rotation=0)
for bar in ax.patches:
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 5,
            f"{int(bar.get_height()):,}", ha="center", va="bottom", fontsize=9)
plt.tight_layout()
plt.show()

"""## 4. Data Preprocessing


"""

columns_to_drop = ["id", "on_dialysis", "dialysis_type", "ckd_stage"]

df = df.drop(columns=columns_to_drop)

print(f"Columns dropped: {columns_to_drop}")
print(f"Remaining shape: {df.shape}")

"""### 4.2 Feature and Target Separation


"""

target = "outcome"

X = df.drop(columns=[target])
y = df[target]

# One-hot encode categorical features
X = pd.get_dummies(X, drop_first=True)

# Integer-encode the target
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

print(f"Feature matrix shape: {X.shape}")
print(f"Classes (encoded order): {list(label_encoder.classes_)}")

"""### 4.3 Train / Test Split


"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    stratify=y   # critical for imbalanced data
)

print(f"Training samples : {len(X_train):,}")
print(f"Test samples     : {len(X_test):,}")
print(f"Feature count    : {X_train.shape[1]}")

"""## 5. Baseline Models

### 5.1 Random Forest
"""

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=RANDOM_STATE
)

rf.fit(X_train, y_train)
rf_predictions = rf.predict(X_test)
rf_accuracy    = accuracy_score(y_test, rf_predictions)

print(f"Random Forest — Accuracy: {rf_accuracy:.4f}")
print()
print(classification_report(
    y_test,
    rf_predictions,
    target_names=label_encoder.classes_
))

"""### 5.2 XGBoost"""

xgb = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="multi:softmax",
    num_class=len(label_encoder.classes_),
    random_state=RANDOM_STATE,
    verbosity=0
)

xgb.fit(X_train, y_train)
xgb_predictions = xgb.predict(X_test)
xgb_accuracy    = accuracy_score(y_test, xgb_predictions)

print(f"XGBoost — Accuracy: {xgb_accuracy:.4f}")
print()
print(classification_report(
    y_test,
    xgb_predictions,
    target_names=label_encoder.classes_
))

"""### 5.3 Baseline Comparison & Confusion Matrix"""

# --- Side-by-side accuracy summary ---
baseline_results = pd.DataFrame({
    "Model": ["Random Forest", "XGBoost"],
    "Accuracy": [rf_accuracy, xgb_accuracy]
})
print(baseline_results.to_string(index=False))

# --- Confusion matrix for the XGBoost baseline ---
cm = confusion_matrix(y_test, xgb_predictions)

plt.figure(figsize=(6, 5))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=label_encoder.classes_,
    yticklabels=label_encoder.classes_,
    cmap="Blues"
)
plt.title("XGBoost Baseline — Confusion Matrix", weight="bold")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.tight_layout()
plt.show()

# The pattern here is diagnostic: the model almost certainly over-predicts
# 'stable' and has poor recall on 'esrd' and 'died'. This motivates the
# class-imbalance work in Section 6.

"""### 5.4 Random Forest Feature Importance


"""

importance_df = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
}).sort_values("Importance", ascending=False)

print("Top 10 features by RF impurity importance:")
print(importance_df.head(10).to_string(index=False))

fig, ax = plt.subplots(figsize=(8, 6))
sns.barplot(
    data=importance_df.head(10),
    x="Importance",
    y="Feature",
    palette="viridis",
    ax=ax
)
ax.set_title("Top 10 Most Important Features (Random Forest)", weight="bold")
ax.set_xlabel("Mean Decrease in Impurity")
plt.tight_layout()
plt.show()

"""## 6. Addressing Class Imbalance using SMOTE (Synthetic Minority Over-sampling Technique)"""

# SMOTE + XGBoost pipeline (imbalance-aware)
smote_pipeline = Pipeline([
    ("smote", SMOTE(random_state=RANDOM_STATE)),
    ("model", XGBClassifier(
        objective="multi:softprob",
        eval_metric="mlogloss",
        random_state=RANDOM_STATE,
        n_estimators=300,
        max_depth=5,
        learning_rate=0.05,
        verbosity=0
    ))
])

cv = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)

smote_cv_scores = cross_val_score(
    smote_pipeline,
    X, y,
    cv=cv,
    scoring="f1_macro",
    n_jobs=-1
)

print(f"SMOTE + XGBoost — Cross-validation Macro F1 per fold: {smote_cv_scores.round(4)}")
print(f"Mean Macro F1: {smote_cv_scores.mean():.4f} ± {smote_cv_scores.std():.4f}")

# Visualise fold-by-fold stability
plt.figure(figsize=(7, 4))
plt.plot(range(1, N_SPLITS + 1), smote_cv_scores, marker="o", linewidth=2, color="#4C72B0")
plt.axhline(smote_cv_scores.mean(), linestyle="--", color="grey", label=f"Mean = {smote_cv_scores.mean():.3f}")
plt.title("SMOTE + XGBoost — Cross-Validation F1 per Fold", weight="bold")
plt.xlabel("Fold")
plt.ylabel("Macro F1 Score")
plt.legend()
plt.tight_layout()
plt.show()

"""## 7. Macro F1 Evaluation of Baseline Models


"""

# Fit the SMOTE pipeline on training data for held-out test predictions
smote_pipeline.fit(X_train, y_train)
pipeline_pred = smote_pipeline.predict(X_test)

# Compute macro F1 for all three models
rf_f1       = f1_score(y_test, rf_predictions, average="macro")
xgb_f1      = f1_score(y_test, xgb_predictions, average="macro")
pipeline_f1 = f1_score(y_test, pipeline_pred, average="macro")

comparison = pd.DataFrame({
    "Model": ["Random Forest", "XGBoost", "SMOTE + XGBoost"],
    "Accuracy": [
        accuracy_score(y_test, rf_predictions),
        accuracy_score(y_test, xgb_predictions),
        accuracy_score(y_test, pipeline_pred)
    ],
    "Macro F1": [rf_f1, xgb_f1, pipeline_f1]
}).round(4)

print(comparison.to_string(index=False))

fig, ax = plt.subplots(figsize=(7, 4))
ax.bar(comparison["Model"], comparison["Macro F1"], color=["#4C72B0","#DD8452","#55A868"], edgecolor="white")
ax.set_ylabel("Macro F1 Score")
ax.set_title("Macro F1 Score — Baseline Model Comparison", weight="bold")
ax.set_ylim(0, max(comparison["Macro F1"]) * 1.2)
for bar, val in zip(ax.patches, comparison["Macro F1"]):
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.005,
            f"{val:.4f}", ha="center", fontsize=9)
plt.tight_layout()
plt.show()

"""## 8. Advanced Models with Feature Selection

### 8.1 Feature Selection via Mutual Information
"""

mi_scores = mutual_info_classif(X, y, random_state=RANDOM_STATE)

mi_df = pd.DataFrame({
    "Feature": X.columns,
    "MI Score": mi_scores
}).sort_values("MI Score", ascending=False).reset_index(drop=True)

print("Top 15 features by Mutual Information:")
print(mi_df.head(15).to_string(index=False))

# Visualise MI scores
fig, ax = plt.subplots(figsize=(8, 5))
sns.barplot(data=mi_df.head(15), x="MI Score", y="Feature", palette="mako", ax=ax)
ax.set_title("Top 15 Features — Mutual Information with Outcome", weight="bold")
plt.tight_layout()
plt.show()

# Keep only the top 15 features for the advanced models
top_features = mi_df.head(15)["Feature"].tolist()
X_selected   = X[top_features]

print(f"Reduced feature set: {len(top_features)} features")
print(top_features)

"""### 8.2 Balanced Random Forest


"""

brf = BalancedRandomForestClassifier(
    n_estimators=400,
    random_state=RANDOM_STATE
)

scores_brf = cross_val_score(
    brf,
    X_selected, y,
    cv=cv,
    scoring="f1_macro",
    n_jobs=-1
)

print(f"Balanced Random Forest — Macro F1 per fold: {scores_brf.round(4)}")
print(f"Mean Macro F1 : {scores_brf.mean():.4f} ± {scores_brf.std():.4f}")

"""### 8.3 LightGBM with Class Weighting


"""

lgb_model = lgb.LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    class_weight="balanced",
    random_state=RANDOM_STATE,
    verbose=-1
)

scores_lgb = cross_val_score(
    lgb_model,
    X_selected, y,
    cv=cv,
    scoring="f1_macro",
    n_jobs=-1
)

print(f"LightGBM — Macro F1 per fold: {scores_lgb.round(4)}")
print(f"Mean Macro F1 : {scores_lgb.mean():.4f} ± {scores_lgb.std():.4f}")

"""## 9. Final Model Comparison


"""

final_results = pd.DataFrame({
    "Model": [
        "Random Forest (baseline)",
        "XGBoost (baseline)",
        "SMOTE + XGBoost",
        "Balanced Random Forest",
        "LightGBM (class-weighted)"
    ],
    "Evaluation": [
        "Hold-out test set",
        "Hold-out test set",
        "Hold-out test set",
        "5-fold CV",
        "5-fold CV"
    ],
    "Macro F1": [
        rf_f1,
        xgb_f1,
        pipeline_f1,
        scores_brf.mean(),
        scores_lgb.mean()
    ]
}).round(4)

print(final_results.to_string(index=False))

colours = ["#9ecae1","#9ecae1","#fdae6b","#a1d99b","#31a354"]

fig, ax = plt.subplots(figsize=(10, 5))
bars = ax.bar(final_results["Model"], final_results["Macro F1"],
              color=colours, edgecolor="white", width=0.6)
ax.set_ylabel("Macro F1 Score")
ax.set_title("Final Model Comparison — Macro F1 Score", weight="bold", fontsize=13)
ax.set_ylim(0, final_results["Macro F1"].max() * 1.2)
ax.tick_params(axis="x", rotation=20)
for bar, val in zip(bars, final_results["Macro F1"]):
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.003,
            f"{val:.4f}", ha="center", fontsize=9)
plt.tight_layout()
plt.show()

"""## 10. Best Model Deep-Dive: LightGBM

### 10.1 Confusion Matrix
"""

# Train on the train split for a fair held-out evaluation
lgb_final = lgb.LGBMClassifier(
    class_weight="balanced",
    random_state=RANDOM_STATE,
    verbose=-1
)
lgb_final.fit(X_train, y_train)
lgb_pred = lgb_final.predict(X_test)

cm = confusion_matrix(y_test, lgb_pred)

fig, ax = plt.subplots(figsize=(6, 5))
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=label_encoder.classes_
)
disp.plot(ax=ax, colorbar=True, cmap="Blues")
ax.set_title("LightGBM (class-weighted) — Confusion Matrix", weight="bold")
plt.tight_layout()
plt.show()

print()
print(classification_report(y_test, lgb_pred, target_names=label_encoder.classes_))

"""### 10.2 Feature Importance


"""

# Note: we fit the final model on X_train (full feature set) for this plot
lgb_full = lgb.LGBMClassifier(
    class_weight="balanced",
    random_state=RANDOM_STATE,
    verbose=-1
)
lgb_full.fit(X_train, y_train)

importance_lgb = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": lgb_full.feature_importances_
}).sort_values("Importance", ascending=False)

fig, ax = plt.subplots(figsize=(9, 6))
sns.barplot(data=importance_lgb.head(15), x="Importance", y="Feature",
            palette="viridis", ax=ax)
ax.set_title("LightGBM — Top 15 Feature Importances (Split Count)", weight="bold")
ax.set_xlabel("Split Count")
plt.tight_layout()
plt.show()